<?php

namespace Packt\PacktAuth;

use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Packt\PacktAuth\Commands\PacktAuthCommand;

class PacktAuthServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('packt-auth')
            ->hasViews()
            ->hasRoute('web')
            ->hasMigration('add_azure_auth_columns');
    }


    public function register()
    {
        $this->mergeConfigFrom(
            __DIR__.'/../config/packt-auth.php',
            'services.azure'
        );

        $userModel = app()->make('config')->get('auth.providers.users.model');


        return parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        return parent::boot(); // TODO: Change the autogenerated stub
    }
}
